layout_spectrum: 0.6524889
typography_spectrum: 0.02506251
color:
  saturation: 0.4884114
  lightness: 0.4316472
  brandStrength: 0.07109887
  rhythmicContrast: 0.5271495
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Abram
